package main.java.com.dougron.mucus.algorithms.random_melody_generator;

public enum Parameter
{
	PHRASE_LENGTH, TIME_SIGNATURE, PHRASE_START_PERCENT, PHRASE_END_PERCENT, 
	STRUCTURE_TONE_SPACING, TEMPO, XMLKEY, START_NOTE, STRUCTURE_TONE_CONTOUR, 
	STRUCTURE_TONE_MULTIPLIER, CHORD_LIST_GENERATOR, EMBELLISHMENT_CLEARANCE, EMBELLISHMENT_REPETITION_PATTERN, MUG_LISTS,
//	MUG_COUNT_0, MUG_COUNT_1, MUG_COUNT_2, MUG_COUNT_3,
//	MUG_PITCH_0, MUG_PITCH_1, MUG_PITCH_2, MUG_PITCH_3,
//	MUG_RHYTHM_0, MUG_RHYTHM_1, MUG_RHYTHM_2, MUG_RHYTHM_3, 
	MUG_LIST_COUNT, MUG_LIST_RHYTHM, MUG_LIST_PITCH, 
	USE_STRUCTURE_TONE_SYNCOPATOR, STRUCTURE_TONE_SYNCOPATION, 
	TESSITURA
}
