package main.java.com.dougron.mucus.mu_framework.mu_tags;

public enum MuTag
{
	PRINT_CHORDS, 
	
	IS_SYNCOPATION, IS_CHORD_TONE, IS_EXTENDED_CHORD_TONE, 
	IS_SCALE_TONE, IS_NON_SCALE_TONE, IS_LOWER_CHROMATIC_APPROACH_TONE, IS_UPPER_CHROMATIC_APPROACH_TONE, 
	IS_UPPER_DIATONIC_APPROACH_TONE, IS_LOWER_DIATONIC_APPROACH_TONE, IS_APPROACH_TONE, IS_PASSING_TONE, 
	IS_LOWER_NEIGHBOUR_TONE, IS_UPPER_NEIGHBOUR_TONE, IS_ENCLOSURE_1, IS_ENCLOSURE_2, IS_CHORD_TONE_EMBELLISHMENT,
	
	UNACCENTED, ACCENTED, 
	
	IS_ESCAPE_TONE, IS_ANTICIPATION, IS_OCTAVE_ANTICIPATION, 
	
	PHRASE_START, PHRASE_END, IS_SHORT_NOTE, IS_STRUCTURE_TONE, 
	
	STEP_JUMP, JUMP_STEP, 
	
	HAS_MULTIPART_CHILDREN, 
	
	PART_MELODY, PART_CHORDS, PART_DRUMS, PART_BASS, 
	
	CLOSED_HIHAT, KICK_DRUM, SNARE_DRUM, BASS_NOTE, 
	
	BASS_CLEF, TREBLE_CLEF,
	
	PART_1, PART_2, PART_KIK, PART_SNARE, PART_HAT,
	
//	BEAT_STRENGTH_0, BEAT_STRENGTH_1, BEAT_STRENGTH_2, BEAT_STRENGTH_3, BEAT_STRENGTH_4 	// related to MuTagMaps but currently not used
	
	BEAT_STRENGTH, DYNAMIC_ACCENT,
	
	CONTROLLER_LP
}
